### ISSUE TITLE
codes

### ISSUE THREAD

**Issue by lw3259111** [rdevon/DIM#1]
Thanks for your code about DIM,but i feel puzzled for your code, can you give me a code with pytorch? thanks.

**Comment by rdevon** [comment]
Everything that you need to know is in pytorch, except maybe the DCGAN architecture, which is standard and can be found here:
https://github.com/rdevon/cortex/blob/master/cortex/built_ins/networks/convnets.py

or the fully connected network:
https://github.com/rdevon/cortex/blob/master/cortex/built_ins/networks/fully_connected.py

Everything else in cortex just takes care of boilerplate and is standard.
