### ISSUE TITLE
Is Eq. 8 in the paper correct?

### ISSUE THREAD

**Issue by ajtejankar** [rdevon/DIM#12]
Hello,

Thanks for a great paper. I am not sure, but I think the Eq. 8 in the paper doesn't contain correct term for local DIM.

![deep-info-max](https://user-images.githubusercontent.com/3609566/55993736-d6726780-5c7d-11e9-8ab3-53ff3787a4ca.jpg)

Also, in the MINE paper MI is calculated by shuffling `z` along the batch dimension (this mentioned in a footnote) for product of the marginals term. Is there any reason for not doing this?

**Comment by rdevon** [comment]
You're right, those should match. That's a typo.

Shuffling is fine, and I've done that before. It's just faster (though more memory intensive) to just generate all possible negative samples from a batch using matrix multiplication

**Comment by ajtejankar** [comment]
Okay. I'll close the issue.

Thanks a lot.

Edit: Oh, I can't close the issue. Feel free to close it.
