### ISSUE TITLE
work with network after training

### ISSUE THREAD

**Issue by masoudpz** [rdevon/DIM#16]
Hi again.
How can I send an Image into network and get out-put vector (Mutual Information) and loss value for my Input?
I want to use my trained network, Is it possible?

**Comment by rdevon** [comment]
In principle you can just access your network through the .t7 checkpoint file, in which you can find all relevant parameters. You can just load the parameters onto the network the normal way in pytorch.

**Comment by rdevon** [comment]
Closing this.
