### ISSUE TITLE
Hi and thanks for your paper, I see this error when i run pip install .  Could not find a version that satisfies the requirement cortex==0.13a0 (from cortex-DIM==0.13) (from versions: 0.1a0, 0.11) No matching distribution found for cortex==0.13a0 (from cortex-DIM==0.13)  What's wrong?

### ISSUE THREAD

**Issue by duan348733684** [rdevon/DIM#17]
Hi and thanks for your paper, I see this error when i run pip install .

Could not find a version that satisfies the requirement cortex==0.13a0 (from cortex-DIM==0.13) (from versions: 0.1a0, 0.11) No matching distribution found for cortex==0.13a0 (from cortex-DIM==0.13)

What's wrong?

**Comment by rdevon** [comment]
Did you install the `dev` branch of cortex?

**Comment by rdevon** [comment]
I'm going to assume that this is due to not installing the `dev` branch correctly or from PYTHONPATH confusion.
