### ISSUE TITLE
KeyError: '`torchvision` not found in .cortex.yml data_paths'

### ISSUE THREAD

**Issue by duan348733684** [rdevon/DIM#18]
Traceback (most recent call last):
  File "scripts/main.py", line 66, in <module>
    run(controller)
  File "/root/anaconda3/lib/python3.6/site-packages/cortex/main.py", line 38, in run
    data.setup(**exp.ARGS['data'])
  

when i run  python scripts/main.py local classifier --d.source CIFAR10 -n DIM_CIFAR10 --t.epochs 1000       can you help me?                                                                                                                                         File "/root/anaconda3/lib/python3.6/site-packages/cortex/_lib/data/__init__.py", line 69, in setup
    plugin.handle(source, **data_args_)
  File "/root/anaconda3/lib/python3.6/site-packages/cortex/built_ins/datasets/torchvision_datasets.py", line 85, in handle
    torchvision_path = self.get_path('torchvision')
  File "/root/anaconda3/lib/python3.6/site-packages/cortex/plugins.py", line 104, in get_path
    '`{}` not found in {} data_paths'.format(source, _config_name))
KeyError: '`torchvision` not found in .cortex.yml data_paths'

**Comment by rdevon** [comment]
Did you run `cortex setup`? This will build the `~/.cortex.yml` file that will contain custom paths for datasets and output directories. If you did run this, you might have skipped over the part where it was asking for the torchvision dataset path. All the torchvision datasets, which include CIFAR10, etc will be automatically downloaded to and stored there for use with this repo.

**Comment by rdevon** [comment]
I'm going to assume this was due to not properly defining the torchvision dataset fields in the `~.cortex.yml` file.
