### ISSUE TITLE
Training a generator by matching to a prior implicitly

### ISSUE THREAD

**Issue by lw3259111** [rdevon/DIM#2]
Thanks for your codes, Now ,I had reproduced the code with tf, but i feel confused in the "Training a generator by matching to a prior implicitly" section, so, Can your give some example code or reference?
Thanks for your again.

**Comment by rdevon** [comment]
So, this part essentially is training the encoder like the generator from a GAN:
https://github.com/rdevon/cortex/blob/master/cortex/built_ins/models/gan.py
With the "real" coming from a noise distribution that is specified a-priori (in our case, a uniform over (0,1)^d where d is the output dim of the encoder).

In this repo, this is specified:
1) Define the noise "prior", uniform 0,1 in our experiments: https://github.com/rdevon/DIM/blob/master/DIM.py#L69

2) "Generate fake": https://github.com/rdevon/DIM/blob/master/DIM.py#L144
Note that the encoder uses a sigmoid activation function for this step.

3) Train the discriminator on real and fake:
https://github.com/rdevon/DIM/blob/master/DIM.py#L145-L146

4) Train the encoder as a generator of 0,1 noise: 
https://github.com/rdevon/DIM/blob/master/DIM.py#L99-L101

All of this isn't totally necessary, as beta=0 works well, though for some applications a prior might be desirable.
