### ISSUE TITLE
problem in installing DIM

### ISSUE THREAD

**Issue by masoudpz** [rdevon/DIM#21]
Hi Dr,
I've cloned your repo and although i've cloned cortex-dev branch I get 
```
Could not find a version that satisfies the requirement cortex==0.13a0 (from cortex-DIM==0.13) (from versions: 0.1a0, 0.11)
No matching distribution found for cortex==0.13a0 (from cortex-DIM==0.13)
```
again.what is your idea?

**Comment by LiUzHiAn** [comment]
Change `install_requires=['cortex==0.13a0']` into `install_requires=['cortex']` in `setup.py` seems work.

But a better way is to clone cortex-dev first and install cortex-dev via `pip install .`(assume you are in the root path of the cortex-dev repo ).

**Comment by yuu-Wang** [comment]
> Change `install_requires=['cortex==0.13a0']` into `install_requires=['cortex']` in `setup.py` seems work.
> 
> But a better way is to clone cortex-dev first and install cortex-dev via `pip install .`(assume you are in the root path of the cortex-dev repo ).

Did you run out? I need your help. Thank you!
