### ISSUE TITLE
Question about sampling the x' (negative samples) & code. 

### ISSUE THREAD

**Issue by WOWNICE** [rdevon/DIM#39]
Hi, 

I've read your paper, which is quite inspiring! 
But here I have some questions regarding the eq.4, which states "x' is an input sampled from \tilde{P} x P". Does it mean that we randomly pick (x,y) independently from the X and Y(Y is the generated representation distribution of X)? If so, which part of the code implements this sampling method? 

Thanks a lot!

**Comment by rdevon** [comment]
x and x' are just sampled independently of each other, so for instance two different images in a batch where there are no dependencies on how different samples in the batch were sampled.

**Comment by rdevon** [comment]
meaning x' and x (together) are sampled from product of marginals P x P_tilde. P_tilde is just a placeholder for a "copy" of P

**Comment by WOWNICE** [comment]
Ahhh! Got it!

**Comment by WOWNICE** [comment]
Thanks for your kind reply!
