### ISSUE TITLE
a bug in paper?

### ISSUE THREAD

**Issue by bojone** [rdevon/DIM#4]
in paper page 12, table 6.

you show for Pearson chi2, f(u)=(u-1)^2. the domain of f* is R. 
But actually domain of f* is (2, +infty) because we have constraints u > 0 in your paper.

**Comment by rdevon** [comment]
Are you reading the right paper? There's no mention of chi2 nor a Table 6

**Comment by bojone** [comment]
oh, sorry. I confuse it with f-GAN paper (because your result refers f-GAN's results). that is f-GAN's bug.
