### ISSUE TITLE
when will you update your code?

### ISSUE THREAD

**Issue by Gogumee** [rdevon/DIM#6]
Thank you for your good research :)

**Comment by rdevon** [comment]
Code should be fully updated by the end of next week. We didn't do much over the holidays. Mostly we are working on making the code very clear.

**Comment by rdevon** [comment]
[UPDATE] Refactor is going slower than I hoped.  I made some major refactors to the code to separate anything built in from cortex as well as simplify architectures. I will begin pushing code in batches starting either tonight or tomorrow. The pushes will roughly contain these updates in this order:

1) Latest code for dot-product style scoring function and NCE / DV losses for the single global and multiple global settings (tonight or tomorrow). Convnet and folded convnet (strided crops) architectures. Local-only DIM.
2) Resnet and folded resnet architectures and training classifiers keeping the encoder fixed (evaluation).
3) NDM, MINE, SVM, and MS-SSIM evaluation.
4) Global DIM and prior matching.
5) Coordinate and occlusion tasks.

I should be able to get through 4) by the end of next week. 5) sometime the following week. Thanks for your patience!

**Comment by rdevon** [comment]
I've made the first major update, so I'm closing this. The TODOs will slowly be finished over the next few weeks.
