### ISSUE TITLE
a bug in the code?

### ISSUE THREAD

**Issue by Cory-M** [rdevon/DIM#8]
thanks a lot for your amazing work! However, as I tried to run the code, it raised the error:
```
 File "deep_infomax.py", line 107, in build
    self.classifier_c.build(dim_in=conv_units * conv_x * conv_y)
  File "XXX/.local/lib/python3.6/site-packages/cortex/_lib/models.py", line 186, in wrapped
    return fn(*args, **kwargs)
File "XXX/.local/lib/python3.6/site-packages/cortex/built_ins/models/classifier.py", line 35, in build
    classifier = FullyConnectedNet(dim_in, dim_out=dim_l, **classifier_args)
TypeError: type object argument after ** must be a mapping, not NoneType
```
I didn't change anything neither in _cortex_ nor in _DIM_; since I couldn't find the \_\_init\_\_ in class _SimpleClassifier_, I have no idea about how to fix the bug. Would you mind checking that?

**Comment by rdevon** [comment]
Give me a day or two: the backend changed I need to update.
(this will be accompanied by a number of features in the TODO)

**Comment by hendrycks** [comment]
> (this will be accompanied by a number of features in the TODO)

Good to hear!

**Comment by rdevon** [comment]
Sorry for the delay! I'm still working on putting out a solid next release. For those who are still experiencing problems, please revert to an earlier version of cortex until I get this finally pushed out.

**Comment by rdevon** [comment]
I've pushed a lot of changes. Things should work now, and there are more features.
https://github.com/rdevon/DIM/commit/e6622e1de4dc9e15ab4fbb8f72ad495a813e780e

Let me know if your problems in this issue are fixed.

**Comment by yuu-Wang** [comment]
> thanks a lot for your amazing work! However, as I tried to run the code, it raised the error:
> 
> ```
>  File "deep_infomax.py", line 107, in build
>     self.classifier_c.build(dim_in=conv_units * conv_x * conv_y)
>   File "XXX/.local/lib/python3.6/site-packages/cortex/_lib/models.py", line 186, in wrapped
>     return fn(*args, **kwargs)
> File "XXX/.local/lib/python3.6/site-packages/cortex/built_ins/models/classifier.py", line 35, in build
>     classifier = FullyConnectedNet(dim_in, dim_out=dim_l, **classifier_args)
> TypeError: type object argument after ** must be a mapping, not NoneType
> ```
> 
> I didn't change anything neither in _cortex_ nor in _DIM_; since I couldn't find the __init__ in class _SimpleClassifier_, I have no idea about how to fix the bug. Would you mind checking that?

Can you run out successfully? I urgently need your help. Thank you!
