### ISSUE TITLE
code for tiny imagenet

### ISSUE THREAD

**Issue by Cory-M** [rdevon/DIM#9]
hi! would you mind providing the network details(arch, feature map layer, etc) of DIM on tiny-imagenet? the paper only mentioned AlexNet arch, but we don't know which feature map to adopt and we are having trouble reproducing its performance. Sincerely thanks!

**Comment by rdevon** [comment]
So for TinyImagenet, it was exactly the same as STL10. The encoder_config is "alex64x64" and all the default layers there.

I need some details to help (scripts run, etc), as I've received similar feedback for STL10 which I almost have sorted out.

Also, there's an issue with NCE and pytorch version which I haven't sorted out yet: 1.0 tends to have worse performance than with 0.4.1.

**Comment by rdevon** [comment]
Is this still an issue?

**Comment by Cory-M** [comment]
No, I adopted the structure the same as STL10, and it seems working now. Thanks a lot for the kind suggestion!
